# A Gentle Introduction to Keras (Udemy)

This work does predictive modeling using deeplearning with tensorflow in the backend.

## Step 1. Import modules

In [86]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import numpy
from sklearn.model_selection import train_test_split

## Step 2. Set a random seed

Setting up the seed will enable us to get the same output with the model we are going to build. Random numbers are created but if we set same starting ( i.e. set seed ) then we can get the same set of random numbers.

In [87]:
seed = 10 # any value is OK
numpy.random.seed(seed)

## Step 3.  Import the data set

In [88]:
from pandas import read_csv
filename = "BBCN.csv"
dataframe = read_csv(filename)

Check the dataframe

In [89]:
dataframe.head() # first few rows of values are displayed

MaritalStatus  Gender  YearlyIncome  TotalChildren  NumberChildrenAtHome  \
0              5       1           9.0              2                     0   
1              5       1           6.0              3                     3   
2              5       1           6.0              3                     3   
3              5       2           7.0              0                     0   
4              5       2           8.0              5                     5   

   EnglishEducation  HouseOwnerFlag  NumberCarsOwned  CommuteDistance  Region  \
0                 5               1                0                2       2   
1                 5               0                1                1       2   
2                 5               1                1                5       2   
3                 5               0                1               10       2   
4                 5               1                4                2       2   

   Age  BikeBuyer  
0    5          1  
1    4          1  
2    4          1  
3    5          1  
4    5          1

What are the columns in the dataframe?

In [90]:
dataframe.columns

Index([u'MaritalStatus', u'Gender', u'YearlyIncome', u'TotalChildren',
       u'NumberChildrenAtHome', u'EnglishEducation', u'HouseOwnerFlag',
       u'NumberCarsOwned', u'CommuteDistance', u'Region', u'Age',
       u'BikeBuyer'],
      dtype='object')

Check the first dataframe row

In [91]:
dataframe.iloc[0]

MaritalStatus           5.0
Gender                  1.0
YearlyIncome            9.0
TotalChildren           2.0
NumberChildrenAtHome    0.0
EnglishEducation        5.0
HouseOwnerFlag          1.0
NumberCarsOwned         0.0
CommuteDistance         2.0
Region                  2.0
Age                     5.0
BikeBuyer               1.0
Name: 0, dtype: float64

In [92]:
dataframe.columns


Index([u'MaritalStatus', u'Gender', u'YearlyIncome', u'TotalChildren',
       u'NumberChildrenAtHome', u'EnglishEducation', u'HouseOwnerFlag',
       u'NumberCarsOwned', u'CommuteDistance', u'Region', u'Age',
       u'BikeBuyer'],
      dtype='object')

## Step 4. Split the output variables

In [93]:
array =  dataframe.values
array

array([[5., 1., 9., ..., 2., 5., 1.],
       [5., 1., 6., ..., 2., 4., 1.],
       [5., 1., 6., ..., 2., 4., 1.],
       ...,
       [3., 2., 4., ..., 3., 5., 0.],
       [3., 1., 4., ..., 1., 4., 0.],
       [3., 1., 4., ..., 1., 4., 0.]])

In [94]:
#X = array [:,0:11] # includes ALL rows & first column 'MaritalStatus' to 11th column 'Age' -> input variable
#y = array [:,11] # includes ALL rows & the last column only 'BikeBuyer' -> target variable

X_dim = len(dataframe.columns) -1
X = array [:,:-1] # all except last column
y = array[:,(X_dim):(X_dim+1)]# only the last column


# split X and y to training , testing and validation set

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.5, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.01, random_state=1)

In [95]:
X_val

array([[ 1.,  2.,  4.,  0.,  0.,  1.,  1.,  2., 10.,  1.,  3.],
       [ 2.,  2.,  4.,  0.,  0.,  2.,  0.,  2., 10.,  1.,  3.],
       [ 4.,  1.,  7.,  4.,  0.,  4.,  1.,  2., 10.,  1., 84.]])

In [96]:
len(y_val)

3

## Step 5. Define the model

Models in keras is a sequence of layers.

Dense class -> fully connected layers

input_dim -> number of input columns

kernel_initializer -> means the weights, default values are between 0-0.05 ('uniform' i.e. initialized the 'weights' to a small random number generated from a uniform distibution )
Old example have this parameter as 'init' which is changed to 'kernel_initializer' here, else it will fire a warning

activation-> activation function( relu -> maps input to same output value but negative values are mapped to zero, sigmoid -> does binary classification i.e. Output 0 (for values < 0.5) labelled as class A and 1 (>=0.5) labelled as class B )
Activation functions summary: https://www.youtube.com/watch?v=9vB5nzrL4hY

In [97]:
model = Sequential() # 
# Define 4 layers
model.add(Dense(12,input_dim=X_dim,kernel_initializer='uniform',activation='relu')) # Input layer with 11 neurons
#model.add(Dense(20,input_dim=X_dim,kernel_initializer='uniform',activation='relu')) # hidden layer with 8 neurons
model.add(Dense(8,input_dim=X_dim,kernel_initializer='uniform',activation='relu')) # hidden layer with 8 neurons
model.add(Dense(1,input_dim=X_dim,kernel_initializer='uniform',activation='sigmoid')) # output layer with 1 neuron

## Step 5. Compile the Model


loss -> cost function i.e. 'binary_crossentropy' is the cost function in logistic regression and 'categorical_crossentropy' is for multiclass predictions via softmax. The cost function measures **how close the estimated values are to their real values.**

So, for our model we choose binary_crossentropy

optimizer -> 'adam' i.e. an algorithm for first-order gradient-based optimization of stochastic objective functions, based on adaptive estimates of lower-order moments. https://keras.io/optimizers/

metric -> function to check the model performance i.e. 'accuracy' which is simply the ratio of correctly predicted observations. Using accuracy suitable only for symmetric datasets with the output classes are equally distributed.


In [98]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Step 6. Fit the Model

epochs -> number of passes over the training data ( more passes will improve the predictions)

batch_size -> how many training samples to use while training. For e.g. for 200 training examples, if batch_size is 100, then it will take 2 iterations to complete 1 epoch.

Training a network will find the best set of weights for making predictions.


In [99]:
model.fit(X_train, y_train, epochs = 200, batch_size = 5)

Epoch 1/200
247/247 [==============================] - 0s 1ms/step - loss: 0.6931 - acc: 0.5385 
Epoch 2/200
247/247 [==============================] - 0s 143us/step - loss: 0.6922 - acc: 0.5506
Epoch 3/200
247/247 [==============================] - 0s 145us/step - loss: 0.6911 - acc: 0.5506
Epoch 4/200
247/247 [==============================] - 0s 164us/step - loss: 0.6899 - acc: 0.5506
Epoch 5/200
247/247 [==============================] - 0s 146us/step - loss: 0.6877 - acc: 0.5506
Epoch 6/200
247/247 [==============================] - 0s 150us/step - loss: 0.6859 - acc: 0.5506
Epoch 7/200
247/247 [==============================] - 0s 163us/step - loss: 0.6828 - acc: 0.5506
Epoch 8/200
247/247 [==============================] - 0s 145us/step - loss: 0.6806 - acc: 0.5506
Epoch 9/200
247/247 [==============================] - 0s 145us/step - loss: 0.6752 - acc: 0.5466
Epoch 10/200
247/247 [==============================] - 0s 166us/step - loss: 0.6710 - acc: 0.5830
Epoch 11/200
247/247

247/247 [==============================] - 0s 168us/step - loss: 0.5682 - acc: 0.7085
Epoch 84/200
247/247 [==============================] - 0s 157us/step - loss: 0.5629 - acc: 0.7126
Epoch 85/200
247/247 [==============================] - 0s 159us/step - loss: 0.5599 - acc: 0.7045
Epoch 86/200
247/247 [==============================] - 0s 156us/step - loss: 0.5593 - acc: 0.7085
Epoch 87/200
247/247 [==============================] - 0s 147us/step - loss: 0.5571 - acc: 0.7166
Epoch 88/200
247/247 [==============================] - 0s 136us/step - loss: 0.5624 - acc: 0.6923
Epoch 89/200
247/247 [==============================] - 0s 138us/step - loss: 0.5597 - acc: 0.7126
Epoch 90/200
247/247 [==============================] - 0s 137us/step - loss: 0.5636 - acc: 0.6883
Epoch 91/200
247/247 [==============================] - 0s 135us/step - loss: 0.5654 - acc: 0.7045
Epoch 92/200
247/247 [==============================] - 0s 140us/step - loss: 0.5596 - acc: 0.7045
Epoch 93/200
247/247 [=

247/247 [==============================] - 0s 143us/step - loss: 0.5612 - acc: 0.6964
Epoch 166/200
247/247 [==============================] - 0s 140us/step - loss: 0.5514 - acc: 0.7004
Epoch 167/200
247/247 [==============================] - 0s 143us/step - loss: 0.5345 - acc: 0.7206
Epoch 168/200
247/247 [==============================] - 0s 138us/step - loss: 0.5411 - acc: 0.7206
Epoch 169/200
247/247 [==============================] - 0s 137us/step - loss: 0.5365 - acc: 0.7045
Epoch 170/200
247/247 [==============================] - 0s 137us/step - loss: 0.5411 - acc: 0.7206
Epoch 171/200
247/247 [==============================] - 0s 139us/step - loss: 0.5484 - acc: 0.7206
Epoch 172/200
247/247 [==============================] - 0s 140us/step - loss: 0.5372 - acc: 0.7126
Epoch 173/200
247/247 [==============================] - 0s 139us/step - loss: 0.5374 - acc: 0.7126
Epoch 174/200
247/247 [==============================] - 0s 140us/step - loss: 0.5391 - acc: 0.7126
Epoch 175/200


## Step 7. Score the Model

In [100]:
scores = model.evaluate(X_test,y_test)
print ("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

250/250 [==============================] - 0s 405us/step
acc: 60.40%


Notice the difference in the accuracy percentage with different input files in **step 3** .
When the input is not normalized the accuracy is about 50% **(filename = "BBC.csv")**.
When the input is normalized, the accuracy is improved above 60% **(filename = "BBCN.csv")**.
Using larger epoch value improved accuracy.

### Tuning the Model

1. normalize the data and repeat the process. E.g. Input file = "BBCN.csv" is the normalized form of "BBC.csv" ( column YearlyIncome is normalized ).

2. Add another hidden layer and also change the number of neurons in the layers.

3. Increase the number of epochs.

4. Optimal size of trainig & testing sets.

## Step 8. Make Predictions

Using new input dataset, we can use our model to predict the output.

Need to call the **model.predict()** fucntion. 

As sigmoid activation function is used in the output layer, the predictions will be in the range between 0 and 1. Then, we will convert them into a  binary prediction for our classification needs.

Refer Step 7 in https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/

In [101]:
X_predict = X_val #X_test[0:5,] # Need to give some new data for prediction
predictions = model.predict(X_predict )
rounded = [round(x[0]) for x in predictions] # round predictions
print(rounded)


[1.0, 1.0, 1.0]


In [102]:
y_val

array([[0.],
       [1.],
       [0.]])

## References

https://www.udemy.com/a-gentle-introduction-to-deep-learning-using-keras/

https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
